#!/bin/bash

echo "Make sure that you have the following files:"
echo "libs/jquery.js libs/ol-debug.js libs/jquery.timeago.js libs/flot/jquery.flot.js libs/flot/jquery.flot.time.js"

# CSS
cat static/css/src/style.scss libs/ol.css | sass --stdin --scss | yui-compressor --type css > static/css/main.css

# JS
srcfiles=(libs/jquery.js libs/jquery.timeago.js libs/ol-debug.js libs/flot/jquery.flot.js libs/flot/jquery.flot.time.js static/js/src/map.coffee static/js/src/sidebar.coffee static/js/src/stats.coffee static/js/src/helpers.coffee)
for i in ${!srcfiles[*]}
do
    tmpfiles[$i]=$(mktemp)
    if [[ ${srcfiles[$i]} == *coffee ]]
    then
        coffee -b -c -p ${srcfiles[$i]} > ${tmpfiles[$i]} 
    else
        cat ${srcfiles[$i]} > ${tmpfiles[$i]} 
    fi
done
cat ${tmpfiles[*]} | yui-compressor --type js > static/js/main.js
rm ${tmpfiles[*]}
